# Generated by Django 5.0.6 on 2024-06-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
