# Generated by Django 5.0.6 on 2024-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tag_content_type_remove_tag_object_id'),
        ('store', '0006_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
